### ISSUE TITLE
AttributeError: module 'aiohttp' has no attribute 'web'

### ISSUE THREAD

**Issue by kapsali29** [bentoml/BentoML#1544]
**Describe the bug**

Hi guys. I am new to BentoML and I have downloaded the quickstart guide following the instructions

1. git clone http://github.com/bentoml/bentoml
2. cd bentoml
3. pip install -r ./guides/quick-start/requirements.txt
4. python main.py

and then after executing the command for serving the IrisClassifier `bentoml serve IrisClassifier:latest` I get the following error

```
AttributeError: module 'aiohttp' has no attribute 'web'
```
Any help....

**Environment:**
 - OS: Windows 10 Pro
 - Python 3.7
 - BentoML-0.12.0

**Comment by parano** [comment]
Thanks for reporting this @kapsali29, I'm looking into it

**Comment by parano** [comment]
@kapsali29 what's your aiohttp version?

**Comment by kapsali29** [comment]
@parano thanks for your prompt response. The aiohttp version I use is the 3.7.4

**Comment by bnapora** [comment]
Having this issue as well: aiohttp==3.7.4.post0
Windows 10

**Comment by parano** [comment]
Update: I'm working on releasing 0.12.1 now, which will include the fix for this issue in #1557
